site_name: My Docs
theme:
  name: material
  features:
    - navigation.indexes
plugins:
    - search
    - macros
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
extra:
  YOCTO_BRANCH: kirkstone