site_name: My Docs
theme:
  name: material
plugins:
    - include-markdown:
        dedent: true
    - search
    - macros
    - mkdocs-glossary-plugin:
        glossary_dirs: ["glossary"]
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
extra:
  YOCTO_BRANCH: kirkstone
